cloud:
  aws:
    credentials:
      access-key: AKIA25BTQUZ742XIAJEJ
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: springboot-s31

server:
  port: 8080